### ISSUE TITLE
Refactor header text

### ISSUE THREAD

**Issue by hseritt** [hseritt/django-blog#17]
For header text, create either a messages file or a database entry to contain text.

**Comment by hseritt** [comment]
Need a new branch for this:

RefactorHeaderText17

**Comment by hseritt** [comment]
Was a simple fix in test but in production there was this error:

```
(blog) root@ubuntu:/var/www/html/dev.prodigi.us# ./manage.py makemigrations common
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.pyenv/versions/2.7.12/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/html/dev.prodigi.us/blog/urls.py", line 18, in <module>
    from common.views import about, index
  File "/var/www/html/dev.prodigi.us/common/views.py", line 10, in <module>
    tag_line = PageElement.objects.get(name='Tag Line', is_visible=True)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/root/.pyenv/versions/blog/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: relation "common_pageelement" does not exist
LINE 1: ...t"."text", "common_pageelement"."is_visible" FROM "common_pa...
```

Turns out there was nothing wrong with any of the migrations. The problem was with the fact that the views from both common and posts apps were already using PageElement before it had been introduced into the database via the models. I had to go back and comment out any references to it and then run the migrations and at that point, it worked in prod.

**Comment by hseritt** [comment]
Tested successfully (now) in production.

**Comment by hseritt** [comment]
Done.
