### ISSUE TITLE
Handle import errors in settings.py

### ISSUE THREAD

**Issue by hseritt** [hseritt/django-blog#54]
After downloading and installing in a new environment, we get this error:

```
$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hseritt/.pyenv/versions/django-blog/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/hseritt/.pyenv/versions/django-blog/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/hseritt/.pyenv/versions/django-blog/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/hseritt/.pyenv/versions/django-blog/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/hseritt/.pyenv/versions/django-blog/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/hseritt/.pyenv/versions/django-blog/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hseritt/projects/django-blog/blog/blog/settings.py", line 14, in <module>
    import blog.env as env
ModuleNotFoundError: No module named 'blog.env'
```

**Comment by hseritt** [comment]
We need to move the settings in env file back into settings.py but they can be generic. So that these are *not* used in our own environments, we should do the import at the end of the settings file.

**Comment by hseritt** [comment]
Related to case #37

**Comment by hseritt** [comment]
As far as this is concerned:

```
common.models.DoesNotExist: PageElement matching query does not exist.
```

We need to decide, do we want to keep some of the changes that can be made via DB in this app. If we do, then there needs to be some kind of setup script for it.
